name: Build and Scan Docker Image with Docker Scan

on:
  push:
    branches:
      - '**'                      # Trigger workflow on any branch
  pull_request:
    branches:
      - '**'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image locally
        run: |
          docker buildx build --tag my-app:${{ github.sha }} --load .

      - name: Scan the Docker image using Docker Scan (Snyk)
        run: |
          docker scan my-app:${{ github.sha }}

      - name: Upload scan report
        uses: actions/upload-artifact@v3
        with:
          name: scan-report
          path: scan-report.txt
