name: Build and Scan Docker Image with Trivy

on:
  push:
    branches:
      - '**'                     
  pull_request:
    branches:
      - '**'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image locally
        run: |
          docker buildx build --tag my-app --load .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan the Docker image using Trivy
        run: |
          trivy image my-app
          trivy image --format table --output trivy-scan-report.txt my-app
          
      - name: Generate SBOM in CycloneDX format
        run: |
          trivy image --format cyclonedx --output sbom.xml my-app
        continue-on-error: true  # Bypass failure in SBOM generation

      - name: Generate html format
        run: |
          trivy repo --format template --template "@html.tpl" -o report.html
        continue-on-error: true
        
      - name: Upload Trivy SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.xml

      - name: Upload HTML
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: report.html
          
          
      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-scan-report.txt
