name: Build and Scan Docker Image with Docker Scout

on:
  push:
    branches:
      - '**'                      # Trigger workflow on any branch

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image locally
        run: |
          docker buildx build --tag my-app:${{ github.sha }} --load .

      # Use Docker Scout Action to scan the locally built Docker image
      - name: Scan the Docker image with Docker Scout
        uses: docker/scout-action@v1
        with:
          image: my-app:${{ github.sha }}

      - name: Upload scan report
        uses: actions/upload-artifact@v3
        with:
          name: scout-report
          path: scout-report.txt
