name: Build and Scan Docker Image with Trivy

on:
  push:
    branches:
      - '**'                      # Trigger workflow on any branch
  pull_request:
    branches:
      - '**'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image locally
        run: |
          docker buildx build --tag my-app:${{ github.sha }} --load .
   
      - name: List Docker images
        run: docker images
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.31.3
        with:
          image-ref: 'my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-scan-report.txt
